name: Linux Gcc

on:
  push:
    branches:
    - DemoApp
    paths-ignore:
    - 'cmake/**'
    - '.github/**'
    - 'doc/**'
    - 'samples/**'

jobs:
  Linux_Gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: DemoApp
    - name: checkout submodules
      run : git submodule update --init --recursive 
    - name: Install OpenGL lib  / Requirement for Glfw3
      run : sudo apt-get update && sudo apt-get install libgl1-mesa-dev libx11-dev libxi-dev libxrandr-dev libxinerama-dev libxcursor-dev
    - name: configure
      run: >
        mkdir build && cd build && cmake .. 
        -DCMAKE_C_COMPILER=gcc
        -DCMAKE_CXX_COMPILER=g++
        -DCMAKE_BUILD_TYPE=Release 
    - name: build
      run: cmake --build build --config Release
    - name: ctest
      run: ctest --test-dir build --output-on-failure
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: EzExprEval_Demo_Unix
        path: bin/EzExprEval_Demo_Unix
